const levels = [
    {
        startPos: {
            x: 20,
            y: 300
        },
        ground: [
            { level: 10 },
            { level: 3, isSquareAngle: true },
            { level: 2.5 },
            { level: 2 },
            { level: 1.5 },
            { level: 1 },
            { level: 0.5 },
            { level: 0 },
            { level: 0 },
            { level: 0 },
            { level: 0 },
            { level: 0.5 },
            { level: 1 },
            { level: 1.5 },
            { level: 2 },
            { level: 2 },
            { level: 2 },
            { level: 1.5 },
            { level: 1 },
            { level: 0.5 },
            { level: 0 },
            { level: -0.5 },
            { level: -1 },
            { level: -1 },
            { level: -0.5 },
            { level: 0 },
            { level: 0 },
            { level: 0 },
            { level: 0.5 },
            { level: 1 },
            { level: 1.5 },
            { level: 2 },
            { level: 2 },
            { level: 1, isSquareAngle: true },
            { level: 2, isSquareAngle: true },
            { level: 1.5 },
            { level: 1 },
            { level: 0.5 },
            { level: 0 },
            { level: 0 },
            { level: 0 },
            { level: 0.5 },
            { level: 1 },
            { level: 1.5 },
            { level: 2 },
            { level: 2 },
            { level: -3, isSquareAngle: true },
            { level: -3 },
            { level: 2, isSquareAngle: true },
            { level: 1.5 },
            { level: 1 },
            { level: 0.5 },
            { level: 0 },
            { level: -0.5 },
            { level: -1 },
            { level: -1 },
            { level: -1 },
            { level: -0.5 },
            { level: 0 },
            { level: 0.5 },
            { level: 1 },
            { level: 1.5 },
            { level: 2 },
            { level: 2.5 },
            { level: 3 },
            { level: 3.5 },
            { level: 4 },
            { level: 4 },
        ],
        candles: [32]
    }, 
    {
        startPos: {
            x: 30,
            y: 30
        },
        ground: [
            { level: 10 },
            { level: 7, isSquareAngle: true },
            { level: 6 },
            { level: 5 },
            { level: 4 },
            { level: 3 },
            { level: 2 },
            { level: 1 },
            { level: 0 },
            { level: -1 },
            { level: -2 },
            { level: -3, isSquareAngle: true },
            { level: -3 },
            { level: -2 },
            { level: -1 },
            { level: 0 },
            { level: 1 },
            { level: 2 },
            { level: 3 },
            { level: 3 },
            { level: -1 },
            { level: -3, isSquareAngle: true },
            { level: -3 },
            { level: -3 },
            { level: 1.6, isSquareAngle: true },
            { level: 3.3 },
            { level: 5 },
            { level: 6, isSquareAngle: true },
            { level: 5 },
            { level: 5 },
            { level: 5 },
            { level: 5 },
            { level: 5 },
        ],
        candles: [14, 18, 25]
    },
    {
        startPos: {
            x: 50,
            y: 200
        },
        ground: [
            { level: 10 },
            { level: 3, isSquareAngle: true },
            { level: 2.5 },
            { level: 2 },
            { level: 1.5 },
            { level: 1 },
            { level: .5 },
            { level: 0 },
            { level: 0 },
            { level: 0 },
            { level: 0 },
            { level: -3, isSquareAngle: true },
            { level: -2 },
            { level: -1 },
            { level: 2, isSquareAngle: true },
            { level: 2, isSquareAngle: true },
            { level: 0 },
            { level: 0 },
            { level: -3, isSquareAngle: true },
            { level: -3 },
            { level: -3 },
            { level: -3 },
            { level: 0, isSquareAngle: true },
            { level: 0 },
            { level: 2 },
            { level: 2 },
            { level: 1 },
            { level: 0 },
            { level: -3, isSquareAngle: true },
            { level: -3 },
            { level: -3 },
            { level: 0, isSquareAngle: true },
            { level: 0 },
            { level: 0 },
            { level: 0 },
            { level: 0 },
            { level: 0 },
            { level: 0 },
            { level: 0 },
            { level: 0 },
            { level: 0 },
            { level: 1 },
            { level: 2 },
            { level: 3 },
        ],
    },
]

export {
	levels
}